# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli
[print_schema]
file = "src/model/diesel/dolphin/dolphin_schema.rs"

# This will cause only the users and posts tables to be output
filter = { only_tables = [ "dashboard","admin_users","article"] }

# https://stackoverflow.com/questions/59228152/rust-diesel-cli-setting-up-multiple-env-files-for-different-environments
