# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli


[print_schema]
schema = ["schema1"]
exclude_schemas = ["pg_catalog", "information_schema"] # Implicit defaults include xor exclude
patch_file = ""

[print_schema.schema1]
file = "src/models/schema1.rs"
filter = { except_tables = ["spatial_ref_sys"] }



