// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use rocket::serde::Serialize;
use serde::Deserialize;

use crate::model::diesel::quark::quark_schema::*;

#[derive(Insertable,Queryable,Debug,Serialize,Deserialize,Default)]
#[table_name = "sys_dict"]
pub struct AddSysDict {
    pub key: Option<i32>,
    pub dict_type: String,
    pub value: String,
    pub show_value: String,
    pub dict_type_name: String,
}

