// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use rocket::serde::Serialize;
use serde::Deserialize;

use crate::model::diesel::quark::quark_schema::*;

#[derive(Insertable,Queryable,Debug,Serialize,Deserialize,Default)]
#[diesel(table_name = sys_dict)]
pub struct SysDict {
    pub id: i32,
    pub key: Option<i32>,
    pub dict_type: String,
    pub value: String,
    pub show_value: String,
    pub dict_type_name: String,
}

