// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use rocket::serde::Serialize;
use serde::Deserialize;

use crate::model::diesel::dict::dict_schema::*;

#[derive(Insertable,Queryable,Debug,Serialize,Deserialize,Default)]
#[table_name = "user_dict"]
pub struct CustomUserDict {
    pub word_id: i64,
    pub user_id: i64,
    pub created_time: i64,
    pub updated_time: i64,
    pub status: i32,
    pub word: String,
}

