// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use rocket::serde::Serialize;
use serde::Deserialize;

use chrono::DateTime;
use chrono::offset::Utc;
#[derive(Queryable,Debug,Serialize,Deserialize,Default)]
pub struct AdminUser {
    pub id: i64,
    pub nickname: Option<String>,
    pub avatar_url: Option<String>,
    pub phone: Option<String>,
    pub updated_time: Option<i64>,
    pub created_time: Option<i64>,
    pub salt: Option<String>,
    pub pwd: Option<String>,
    pub sex: Option<i32>,
    pub level_type: Option<String>,
    pub phone_region: Option<String>,
    pub country_code: Option<i32>,
    pub user_status: Option<String>,
}

#[derive(Queryable,Debug,Serialize,Deserialize,Default)]
pub struct App {
    pub id: i32,
    pub app_name: String,
    pub remark: Option<String>,
    pub created_time: i64,
    pub updated_time: Option<i64>,
    pub user_count: Option<i32>,
    pub online_status: Option<i32>,
    pub online_time: Option<i64>,
    pub app_tag: Option<String>,
    pub app_id: i32,
}

#[derive(Queryable,Debug,Serialize,Deserialize,Default)]
pub struct Article {
    pub id: i64,
    pub user_id: i64,
    pub title: String,
    pub author: String,
    pub guid: String,
    pub created_time: i64,
    pub updated_time: i64,
    pub link: Option<String>,
    pub pub_time: Option<DateTime<Utc>>,
    pub sub_source_id: i64,
    pub cover_image: Option<String>,
    pub channel_reputation: i32,
    pub editor_pick: Option<i32>,
}

#[derive(Queryable,Debug,Serialize,Deserialize,Default)]
pub struct ArticleContent {
    pub id: i64,
    pub article_id: i64,
    pub articleContent: String,
}

#[derive(Queryable,Debug,Serialize,Deserialize,Default)]
pub struct Dashboard {
    pub id: i32,
    pub app_count: i32,
    pub user_count: i32,
}

